### ISSUE TITLE
Registrar usuario - paciente - obra social no se carga 

### ISSUE THREAD

**Issue by KatuGT** [AndresRodriguez-98/appointment-schedule#12]
Al registrarme  ingreso obraSocial, ejemplo: Prensa, pero al buscar mi usuario veo la que por "default" aparece en el modelo dle usuario que es "Ioma" 
![image](https://github.com/AndresRodriguez-98/appointment-schedule/assets/38865485/134fa8e0-f226-402a-86b7-ee5c91f80fd2)
![image](https://github.com/AndresRodriguez-98/appointment-schedule/assets/38865485/67714e47-e5b6-4b1f-8c6e-015afc599edd)

**Comment by AndresRodriguez-98** [comment]
Corregido!

**Comment by KatuGT** [comment]
Listo, probado!
